# Generated by Django 3.2.12 on 2022-12-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='friend',
            name='gender',
            field=models.CharField(max_length=100),
        ),
    ]
